package Vista;

import Controlador.Ctrl_Producto;
import Modelo.Producto;
import Controlador.ProductoDAO;
import conexion.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class InterProducto extends javax.swing.JInternalFrame {

    int obtenerIdCategoriaCombo = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterProducto.class.getName());

    ProductoDAO dao = new ProductoDAO();
    DefaultTableModel modelo;

    public InterProducto() {
        initComponents();
        this.CargarComboCategorias();
        modelo = new DefaultTableModel(new Object[]{"IdProducto", "Nombre", "Stock", "Precio", "descripcion", "codigo", "idCategoria"}, 0);
        tablaProductos.setModel(modelo);
        listar();
    }

    void listar() {
        

        List<Producto> lista = dao.listar();
        modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);

        Object[] ob = new Object[7];

        for (Producto p : lista) {
            

            ob[0] = p.getIdProducto();
            ob[1] = p.getNombre();
            ob[2] = p.getStock();
            ob[3] = p.getPrecio();
            ob[4] = p.getDescripcion();
            ob[5] = p.getCodigo();
            ob[6] = p.getIdCategoria();

            modelo.addRow(ob);
        }
    }

    // Limpiar campos
    void limpiar() {
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtDescripcion.setText("");
        txtCodigo.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        lblPrecio1 = new javax.swing.JLabel();
        lblPrecio2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblPrecio3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblPrecio4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jComboBox_categoria = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 206, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 206, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 206, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 206, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 206, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 125, -1));

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio.setText("Categoria:");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 125, -1));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 271, -1, 268));

        lblPrecio1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio1.setText("Stock:");
        getContentPane().add(lblPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        lblPrecio2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio2.setText("Descripcion:");
        getContentPane().add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 125, -1));

        lblPrecio3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio3.setText("Precio: ");
        getContentPane().add(lblPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 125, -1));

        lblPrecio4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecio4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio4.setText("Codigo: ");
        getContentPane().add(lblPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 125, -1));

        jComboBox_categoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria:", "Item 2", "Item 3", "Item 4", " " }));
        jComboBox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Producto producto = new Producto();
        Ctrl_Producto controlProducto = new Ctrl_Producto();
        String categoria = jComboBox_categoria.getSelectedItem().toString().trim();

        // VALIDAR CAMPOS
        if (txtNombre.getText().equals("")
                || txtStock.getText().equals("")
                || txtPrecio.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            txtNombre.setBackground(Color.red);
            txtStock.setBackground(Color.red);
            txtPrecio.setBackground(Color.red);
            txtCodigo.setBackground(Color.red);
            return;
        }

        // VALIDAR SI EL PRODUCTO YA EXISTE
        if (controlProducto.existeProducto(txtNombre.getText().trim())) {
            JOptionPane.showMessageDialog(null, "El producto ya existe en la Base de Datos");
            return;
        }

        // VALIDAR CATEGORÍA
        if (categoria.equalsIgnoreCase("Seleccione categoria:")) {
            JOptionPane.showMessageDialog(null, "Seleccione una categoría");
            return;
        }

        try {
            // SETEAR DATOS AL OBJETO
            producto.setNombre(txtNombre.getText().trim());
            producto.setStock(Integer.parseInt(txtStock.getText().trim()));

            // VALIDAR PRECIO (coma o punto)
            String precioTXT = txtPrecio.getText().trim().replace(",", ".");
            double precio = Double.parseDouble(precioTXT);
            producto.setPrecio(precio);

            producto.setDescripcion(txtDescripcion.getText().trim());
            producto.setCodigo(txtCodigo.getText().trim());

            // OBTENER ID DE CATEGORÍA
            this.IdCategoria();
            producto.setIdCategoria(obtenerIdCategoriaCombo);

            producto.setEstado(1);

            // GUARDAR
            if (controlProducto.guardar(producto)) {
                JOptionPane.showMessageDialog(null, "Registro Guardado");

                txtNombre.setBackground(Color.green);
                txtStock.setBackground(Color.green);
                txtPrecio.setBackground(Color.green);
                txtDescripcion.setBackground(Color.green);
                txtCodigo.setBackground(Color.green);

                this.CargarComboCategorias();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error en el formato del precio o stock");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = tablaProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para actualizar");
            return;
        }
        if (txtPrecio.getText().trim().isEmpty() || txtStock.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return;
        }
        try {
            // OBTENER ID DESDE LA TABLA
            int idProducto = Integer.parseInt(
                    tablaProductos.getValueAt(fila, 0).toString()
            );
            String nombre = txtNombre.getText().trim();
            double precio = Double.parseDouble(
                    txtPrecio.getText().trim().replace(",", ".")
            );
            int stock = Integer.parseInt(txtStock.getText().trim());
            String descripcion = txtDescripcion.getText().trim();
            String codigo = txtCodigo.getText().trim();
            // ID CATEGORÍA
            this.IdCategoria();

            Producto p = new Producto();
            p.setIdProducto(idProducto);   // 🔴 CLAVE
            p.setNombre(nombre);
            p.setStock(stock);
            p.setPrecio(precio);
            p.setDescripcion(descripcion);
            p.setCodigo(codigo);
            p.setIdCategoria(obtenerIdCategoriaCombo);
            p.setEstado(1);

            dao.actualizar(p);
            listar();
            limpiar();

            JOptionPane.showMessageDialog(this, "Producto actualizado Correctamente");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de precio o stock");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar este producto?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            int idProducto = Integer.parseInt(
                    tablaProductos.getValueAt(fila, 0).toString()
            );

            dao.eliminar(idProducto);
            listar();
            limpiar();

            JOptionPane.showMessageDialog(this, "Producto eliminado correctamente");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Desea cerrar sesión?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
            new Vista.LoginFrm().setVisible(true);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        int fila = tablaProductos.rowAtPoint(evt.getPoint());

        txtNombre.setText(tablaProductos.getValueAt(fila, 1).toString());
        txtStock.setText(tablaProductos.getValueAt(fila, 2).toString());    // ✅
        txtPrecio.setText(tablaProductos.getValueAt(fila, 3).toString());   // ✅
        txtDescripcion.setText(tablaProductos.getValueAt(fila, 4).toString());
        txtCodigo.setText(tablaProductos.getValueAt(fila, 5).toString());
        jComboBox_categoria.setSelectedItem(tablaProductos.getValueAt(fila, 6).toString());


    }//GEN-LAST:event_tablaProductosMouseClicked

    private void jComboBox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBox_categoria;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblPrecio4;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    private void CargarComboCategorias() {
        Connection cn = Conexion.conectar();
        String sql = "select * from categoria";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categoria.removeAllItems();
            jComboBox_categoria.addItem("Seleccione categoria:");
            while (rs.next()) {
                jComboBox_categoria.addItem(rs.getString("descripcion"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }
    }

    /**
     *
     * Metodo para obtener id categoria
     */
    private int IdCategoria() {
        String sql = "select * from categoria where descripcion = '" + this.jComboBox_categoria.getSelectedItem() + "'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                obtenerIdCategoriaCombo = rs.getInt("idCategoria");
            }
        } catch (SQLException e) {
            System.out.println("Error al obener id categoria");
        }
        return obtenerIdCategoriaCombo;
    }

    private void Limpiar() {
        txtNombre.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
        txtCodigo.setText("");
        jComboBox_categoria.setSelectedItem("");

    }

}
