package Vista;

import conexion.Conexion;
import Controlador.Ctrl_RegistrarVenta;
import Controlador.VentaPDF;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.CabeceraVenta;
import Modelo.Ventas;

import java.awt.event.*;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author norma
 */
public class InterVentas extends javax.swing.JInternalFrame {

    //Modelo de los datos
    private DefaultTableModel modeloDatosProductos;
    //lista para el detalle de venta de los productos
    ArrayList<Ventas> listaProductos = new ArrayList<>();
    private Ventas producto;

    private int idCliente = 0;//id del cliente sleccionado

    private int idProducto = 0;
    private String nombre = "";
    private int cantidadProductoBBDD = 0;
    private double precioUnitario = 0.0;
    private String formaDePago = "";

    private int cantidad = 0;//cantidad de productos a comprar
    private double totalPagar = 0.0;

    //variables para calculos globales
    private double subtotalGeneral = 0.0;
    private double totalPagarGeneral = 0.0;
    //fin de variables de calculos globales

    private int auxIdDetalle = 1;//id del detalle de venta

    public InterVentas() {
        initComponents();
        this.setSize(new Dimension(800, 600));
        this.setTitle("Facturacion DE VENTA");

        txt_pago.setEnabled(false);
        txt_cambio.setEnabled(false);

        //Cargar lo Clientes en la vista - cargar productos
        this.CargarComboClientes();
        this.CargarComboProductos();

        this.inicializarTablaProducto();

        txt_pago.setEnabled(false);
        jButton_calcular_cambio.setEnabled(false);

        txt_total_pagar.setText("0.0");

        //insertar imagen en nuestro JLabel
        ImageIcon wallpaper = new ImageIcon("src/img/111.jpeg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(800, 600, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
    }

    //metodo para inicializar la tabla de los productos
    private void inicializarTablaProducto() {
        modeloDatosProductos = new DefaultTableModel();
        //añadir columnas
        modeloDatosProductos.addColumn("N");
        modeloDatosProductos.addColumn("Nombre");
        modeloDatosProductos.addColumn("Cantidad");
        modeloDatosProductos.addColumn("P. Unitario");
        modeloDatosProductos.addColumn("Total Pagar");
        modeloDatosProductos.addColumn("Accion");
        //agregar los datos del modelo a la tabla
        this.jTable_productos.setModel(modeloDatosProductos);
    }

    //metodo para presentar la informacion de la tabla DetalleVenta
    private void listaTablaProductos() {
        // Limpiar la tabla antes de llenarla
        modeloDatosProductos.setRowCount(0);

        for (int i = 0; i < listaProductos.size(); i++) {
            modeloDatosProductos.addRow(new Object[]{
                i + 1,
                listaProductos.get(i).getNombre(),
                listaProductos.get(i).getCantidad(),
                listaProductos.get(i).getPrecioUnitario(),
                listaProductos.get(i).getTotalPagar(),
                "Eliminar"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox_cliente = new javax.swing.JComboBox<>();
        jComboBox_producto = new javax.swing.JComboBox<>();
        txt_cliente_buscar = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        jButton_busca_cliente = new javax.swing.JButton();
        jButton_añadir_producto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_total_pagar = new javax.swing.JTextField();
        txt_pago = new javax.swing.JTextField();
        txt_cambio = new javax.swing.JTextField();
        jButton_calcular_cambio = new javax.swing.JButton();
        jComboBox_medioPago = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jButton_RegistrarVenta = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Producto:");

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Cliente:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jComboBox_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione cliente:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, -1));

        jComboBox_producto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, -1));

        txt_cliente_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_cliente_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 150, -1));

        txt_cantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));

        jButton_busca_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_cliente.setText("Buscar");
        jButton_busca_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_busca_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 80, -1));

        jButton_añadir_producto.setBackground(new java.awt.Color(204, 102, 255));
        jButton_añadir_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_añadir_producto.setText("Añadir Productos");
        jButton_añadir_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadir_productoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_añadir_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 150, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_productos.setBackground(new java.awt.Color(204, 255, 204));
        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 540, 400));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total a pagar:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Pago:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cambio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txt_total_pagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_pagar.setEnabled(false);
        jPanel2.add(txt_total_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        txt_pago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, -1));

        txt_cambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cambio.setEnabled(false);
        jPanel2.add(txt_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, -1));

        jButton_calcular_cambio.setBackground(new java.awt.Color(51, 51, 255));
        jButton_calcular_cambio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_calcular_cambio.setText("Calcular Cambio");
        jButton_calcular_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcular_cambioActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_calcular_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 130, 50));

        jComboBox_medioPago.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_medioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione medio de pago:", "EFECTIVO", "TRANSFERENCIA", " " }));
        jComboBox_medioPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_medioPagoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox_medioPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Medio de pago:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 230, 270));

        jButton_RegistrarVenta.setBackground(new java.awt.Color(51, 255, 0));
        jButton_RegistrarVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_RegistrarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jButton_RegistrarVenta.setText("Registrar Venta");
        jButton_RegistrarVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_RegistrarVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_RegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 170, 100));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_busca_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_clienteActionPerformed
        String clienteBuscar = txt_cliente_buscar.getText().trim(); //Obtiene la DNI ingresada por el usuario
        Connection cn = Conexion.conectar(); //Conecta con la base de datos
        String sql = "select nombre, apellido from clientes where dni = '" + clienteBuscar + "'"; //Consulta SQL por cédula
        Statement st;
        try {
            st = cn.createStatement(); //Crea objeto para ejecutar la consulta
            ResultSet rs = st.executeQuery(sql); //Ejecuta la consulta

            if (rs.next()) { //Si encuentra al cliente
                jComboBox_cliente.setSelectedItem(rs.getString("nombre") + " " + rs.getString("apellido")); //Carga nombre completo en el combo
            } else { //Si no existe el cliente
                jComboBox_cliente.setSelectedItem("Seleccione cliente:"); //Vuelve al valor por defecto
                JOptionPane.showMessageDialog(null, "¡Documento de cliente incorrecta o no encontrada!"); //Mensaje de advertencia
            }
            txt_cliente_buscar.setText(""); //Limpia campo de búsqueda
            cn.close(); //Cierra conexión
        } catch (SQLException e) {
            System.out.println("¡Error al buscar cliente!, " + e); //Muestra error
        }
    }//GEN-LAST:event_jButton_busca_clienteActionPerformed

    private void jButton_añadir_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadir_productoActionPerformed

        // ===== VALIDAR CLIENTE =====
        if (jComboBox_cliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
            return;
        }

        // ===== VALIDAR PRODUCTO =====
        if (jComboBox_producto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto");
            return;
        }

        // ===== VALIDAR CANTIDAD VACÍA =====
        if (txt_cantidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad");
            return;
        }

        // ===== VALIDAR QUE SEA NUMÉRICA =====
        if (!validar(txt_cantidad.getText())) {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser numérica");
            return;
        }

        int cantidad = Integer.parseInt(txt_cantidad.getText());

        // ===== VALIDAR MAYOR A CERO =====
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a cero");
            return;
        }

        // ===== OBTENER DATOS DEL PRODUCTO DESDE BD =====
        DatosDelProducto();   // ← USA TU MÉTODO

        // ===== VALIDAR STOCK =====
        if (cantidad > cantidadProductoBBDD) {
            JOptionPane.showMessageDialog(null, "Stock insuficiente");
            return;
        }

        // ===== CALCULAR TOTAL =====
        double totalProducto = precioUnitario * cantidad;
        totalProducto = Math.round(totalProducto * 100) / 100.0;

        // ===== CREAR OBJETO VENTAS =====
        producto = new Ventas(
                auxIdDetalle,
                1,
                idProducto,
                nombre,
                cantidad,
                precioUnitario,
                totalProducto
        );

        // ===== AGREGAR A LA LISTA =====
        listaProductos.add(producto);
        auxIdDetalle++;

        // ===== ACTUALIZAR TABLA =====
        listaTablaProductos();

        // ===== RECALCULAR TOTAL GENERAL =====
        CalcularTotalPagar();

        // ===== CONTROLAR MEDIO DE PAGO =====
        controlarMedioPago();

        // ===== LIMPIAR CAMPOS =====
        txt_cantidad.setText("");
        jComboBox_producto.setSelectedIndex(0);

        JOptionPane.showMessageDialog(null, "Producto agregado correctamente");


    }//GEN-LAST:event_jButton_añadir_productoActionPerformed

    private void jButton_calcular_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcular_cambioActionPerformed
        // 1️⃣ Validar que haya seleccionado medio de pago
        String formaDePago = String.valueOf(jComboBox_medioPago.getSelectedItem());

        if (formaDePago.equals("Seleccione medio de pago")) {
            JOptionPane.showMessageDialog(null, "Seleccione el medio de pago");
            return;
        }

        String medioPago = jComboBox_medioPago.getSelectedItem().toString();

        // ️⃣ Si es transferencia
        if (medioPago.equals("TRANSFERENCIA")) {

            JOptionPane.showMessageDialog(null,
                    "Pago por transferencia registrado.\nNo se calcula vuelto.");

            txt_cambio.setText("0");
            return;
        }

        // 3️⃣ Si es efectivo
        if (medioPago.equals("EFECTIVO")) {

            if (txt_total_pagar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No hay total a pagar");
                return;
            }

            if (txt_pago.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese el monto recibido");
                return;
            }

            try {
                double total = Double.parseDouble(txt_total_pagar.getText());
                double pago = Double.parseDouble(txt_pago.getText());

                if (pago < total) {
                    JOptionPane.showMessageDialog(null,
                            "El monto ingresado es menor al total a pagar");
                    return;
                }

                double cambio = pago - total;
                txt_cambio.setText(String.valueOf(cambio));

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese valores numéricos válidos");
            }
        }
    }//GEN-LAST:event_jButton_calcular_cambioActionPerformed

    int idArrayList = 0;

    private void jTable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productosMouseClicked

        int fila = jTable_productos.rowAtPoint(evt.getPoint());

        if (fila < 0) {
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(null,
                "¿Estas seguro de eliminar el producto?");

        if (opcion == 0) {

            listaProductos.remove(fila);
            CalcularTotalPagar();
            listaTablaProductos();
        }
    }//GEN-LAST:event_jTable_productosMouseClicked

    private void jButton_RegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarVentaActionPerformed

        //cabeceraVenta.setIdUsuario(1);
        // ===== VALIDAR CLIENTE =====
        if (jComboBox_cliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un cliente!");
            return;
        }

        // ===== VALIDAR PRODUCTOS =====
        if (listaProductos.size() == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione al menos un producto!");
            return;
        }

        // ===== VALIDAR MEDIO DE PAGO =====
        if (jComboBox_medioPago.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un medio de pago!");
            return;
        }

        String formaDePago = jComboBox_medioPago.getSelectedItem().toString();

        // ===== SI ES EFECTIVO VALIDAR PAGO =====
        if (formaDePago.equals("EFECTIVO")) {

            if (txt_pago.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "¡Ingrese el monto recibido!");
                return;
            }

            if (!validarDouble(txt_pago.getText())) {
                JOptionPane.showMessageDialog(null, "¡Monto inválido!");
                return;
            }

            double pago = Double.parseDouble(txt_pago.getText());
            double total = Double.parseDouble(txt_total_pagar.getText());

            if (pago < total) {
                JOptionPane.showMessageDialog(null, "¡El monto recibido es menor al total!");
                return;
            }
        }

        // ===== OBTENER ID CLIENTE =====
        this.ObtenerIdCliente();

        // ===== FECHA ACTUAL =====
        String fechaActual = new SimpleDateFormat("yyyy/MM/dd").format(new Date());

        // ===== CREAR CABECERA =====
        CabeceraVenta cabeceraVenta = new CabeceraVenta();
        cabeceraVenta.setIdCabeceraVenta(0);
        cabeceraVenta.setIdCliente(idCliente);
        cabeceraVenta.setFechaVenta(fechaActual);
        cabeceraVenta.setEstado(1);
        cabeceraVenta.setFormaDePago(formaDePago);

        Ctrl_RegistrarVenta controlVenta = new Ctrl_RegistrarVenta();

        // ===== GUARDAR CABECERA =====
        if (controlVenta.guardar(cabeceraVenta)) {

            JOptionPane.showMessageDialog(null, "¡Venta Registrada!");

            // ===== GUARDAR DETALLE =====
            for (Ventas elemento : listaProductos) {

                Ventas detalleVenta = new Ventas();
                detalleVenta.setIdVenta(0);
                detalleVenta.setIdCabeceraVenta(controlVenta.obtenerUltimoId()); // IMPORTANTE
                detalleVenta.setIdProducto(elemento.getIdProducto());
                detalleVenta.setCantidad(elemento.getCantidad());
                detalleVenta.setPrecioUnitario(elemento.getPrecioUnitario());
                detalleVenta.setTotalPagar(elemento.getTotalPagar());

                if (controlVenta.guardarDetalle(detalleVenta)) {

                    // Restar stock
                    this.RestarStockProductos(
                            elemento.getIdProducto(),
                            elemento.getCantidad()
                    );

                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar detalle");
                    return;
                }
            }

            // ===== GENERAR PDF =====
            VentaPDF pdf = new VentaPDF();
            pdf.DatosCliente(idCliente);
            pdf.setFormaDePago(formaDePago);   
            pdf.generarFacturaPDF();

            // ===== LIMPIAR TODO =====
            listaProductos.clear();
            listaTablaProductos();
            auxIdDetalle = 1;

            txt_total_pagar.setText("0.0");
            txt_pago.setText("");
            txt_cambio.setText("");

            jComboBox_cliente.setSelectedIndex(0);
            jComboBox_producto.setSelectedIndex(0);
            jComboBox_medioPago.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(null, "¡Error al guardar cabecera de venta!");
        }

    }//GEN-LAST:event_jButton_RegistrarVentaActionPerformed

    private void jComboBox_medioPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_medioPagoActionPerformed

        controlarMedioPago();


    }//GEN-LAST:event_jComboBox_medioPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_RegistrarVenta;
    private javax.swing.JButton jButton_añadir_producto;
    private javax.swing.JButton jButton_busca_cliente;
    private javax.swing.JButton jButton_calcular_cambio;
    private javax.swing.JComboBox<String> jComboBox_cliente;
    private javax.swing.JComboBox<String> jComboBox_medioPago;
    private javax.swing.JComboBox<String> jComboBox_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JTextField txt_cambio;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cliente_buscar;
    private javax.swing.JTextField txt_pago;
    public static javax.swing.JTextField txt_total_pagar;
    // End of variables declaration//GEN-END:variables

    /*
    Metodo para cargar los clientes en el jComboBox
    


    /*
    Metodo para cargar los clientes en el jComboBox
     */
    private void CargarComboClientes() { // Método que carga clientes en el JComboBox
        Connection cn = Conexion.conectar(); // Establece conexión con la base de datos
        String sql = "select * from clientes"; // Consulta SQL para obtener todos los clientes
        Statement st; // Objeto para ejecutar sentencias SQL
        try { // Bloque que puede generar excepciones
            st = cn.createStatement(); // Se crea el Statement
            ResultSet rs = st.executeQuery(sql); // Se ejecuta la consulta y se guarda el resultado
            jComboBox_cliente.removeAllItems(); // Limpia todos los elementos del ComboBox
            jComboBox_cliente.addItem("Seleccione cliente:"); // Agrega opción inicial
            while (rs.next()) { // Recorre cada registro obtenido
                jComboBox_cliente.addItem(rs.getString("nombre") + " " + rs.getString("apellido")); // Agrega nombre y apellido al ComboBox
            }
            cn.close(); // Cierra la conexión con la base de datos
        } catch (SQLException e) { // Captura errores SQL
            System.out.println("¡Error al cargar clientes, !" + e); // Muestra error en consola
        }
    }


    /*
    Metodo para cargar los productos en el jComboBox
     */
    private void CargarComboProductos() { // Método que carga los productos en el JComboBox
        Connection cn = Conexion.conectar(); // Establece conexión con la base de datos
        String sql = "select * from productos"; // Consulta SQL para obtener todos los productos
        Statement st; // Objeto para ejecutar sentencias SQL
        try { // Bloque que puede generar excepciones
            st = cn.createStatement(); // Se crea el Statement
            ResultSet rs = st.executeQuery(sql); // Se ejecuta la consulta y se guarda el resultado
            jComboBox_producto.removeAllItems(); // Limpia todos los elementos del ComboBox
            jComboBox_producto.addItem("Seleccione producto:"); // Agrega opción inicial
            while (rs.next()) { // Recorre cada registro obtenido
                jComboBox_producto.addItem(rs.getString("nombre")); // Agrega el nombre del producto al ComboBox
            }
            cn.close(); // Cierra la conexión con la base de datos
        } catch (SQLException e) { // Captura errores SQL
            System.out.println("¡Error al cargar productos, !" + e); // Muestra error en consola
        }
    }

    private void controlarMedioPago() {

        if (jComboBox_medioPago.getSelectedItem() == null) {
            return;
        }

        String medioPago = jComboBox_medioPago.getSelectedItem().toString();

        if (medioPago.equals("EFECTIVO")) {

            txt_pago.setEnabled(true);
            txt_cambio.setEnabled(false);
            jButton_calcular_cambio.setEnabled(true);
            txt_cambio.setText("");

        } else if (medioPago.equals("TRANSFERENCIA")) {

            txt_pago.setText(txt_total_pagar.getText());
            txt_pago.setEnabled(false);
            txt_cambio.setText("0");
            txt_cambio.setEnabled(false);
            jButton_calcular_cambio.setEnabled(false);

        } else {

            txt_pago.setEnabled(false);
            txt_cambio.setEnabled(false);
            jButton_calcular_cambio.setEnabled(false);
            txt_pago.setText("");
            txt_cambio.setText("");
        }
    }

    /*
        Metodo para validar que el usuario no ingrese caracteres no numericos
     */
    private boolean validar(String valor) { // Método que valida si un texto puede convertirse en número entero
        try { // Bloque que intenta ejecutar código que puede fallar
            int num = Integer.parseInt(valor); // Convierte el texto a entero
            return true; // Retorna verdadero si la conversión fue exitosa
        } catch (NumberFormatException e) { // Captura error si el texto no es numérico
            return false; // Retorna falso si ocurre error
        }
    }


    /*
        Metodo para validar que el usuario no ingrese caracteres no numericos
     */
    private boolean validarDouble(String valor) {
        try {
            double num = Double.parseDouble(valor);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /*
        Metodo para mostrar los datos del producto seleccionado
     */
    private void DatosDelProducto() { // Método que obtiene los datos del producto seleccionado en el combo
        try { // Bloque para manejar posibles errores
            String sql = "select * from productos where nombre = '" + this.jComboBox_producto.getSelectedItem() + "'"; // Consulta SQL para buscar el producto por nombre
            Connection cn = Conexion.conectar(); // Establece conexión con la base de datos
            Statement st; // Declara objeto Statement
            st = cn.createStatement(); // Crea el Statement
            ResultSet rs = st.executeQuery(sql); // Ejecuta la consulta
            while (rs.next()) { // Recorre el resultado obtenido
                idProducto = rs.getInt("idProducto"); // Obtiene el id del producto
                nombre = rs.getString("nombre"); // Obtiene el nombre del producto
                cantidadProductoBBDD = rs.getInt("stock"); // Obtiene el stock disponible
                precioUnitario = rs.getDouble("precio"); // Obtiene el precio unitario

            }

        } catch (SQLException e) { // Captura error si falla la consulta
            System.out.println("Error al obtener datos del producto, " + e); // Muestra mensaje de error
        }
    }

    /*
    Metodo para calcular el total a pagar de todos los productos agregados
     */
    private void CalcularTotalPagar() {
        // Inicializa acumuladores
        totalPagarGeneral = 0;

        // Recorre todos los productos de la lista
        for (Ventas elemento : listaProductos) {
            // El total a pagar de cada producto ya debería estar calculado
            totalPagarGeneral += elemento.getTotalPagar();
        }

        // Redondear decimales
        totalPagarGeneral = (double) Math.round(totalPagarGeneral * 100) / 100;

        // Mostrar en la vista
        txt_total_pagar.setText(String.valueOf(totalPagarGeneral));

        // Ya no mostramos subtotal, iva ni descuento porque no existen
    }

    /*
    Metodo para obtener id del cliente
     */
    private void ObtenerIdCliente() {

        try {
            Connection cn = Conexion.conectar();

            String sql = "SELECT idCliente FROM clientes "
                    + "WHERE CONCAT(nombre,' ',apellido) = ?";

            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, jComboBox_cliente.getSelectedItem().toString());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                idCliente = rs.getInt("idCliente");
            }

            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al obtener id cliente: " + e);
        }
    }

    //metodo para restar la cantidad (stock) de los productos vendidos
    private void RestarStockProductos(int idProducto, int cantidadVendida) {

        try {
            Connection cn = Conexion.conectar();

            // obtine el stock actual
            String sqlSelect = "SELECT stock FROM productos WHERE idProducto = ?";
            PreparedStatement pstSelect = cn.prepareStatement(sqlSelect);
            pstSelect.setInt(1, idProducto);

            ResultSet rs = pstSelect.executeQuery();

            if (rs.next()) {

                int stockActual = rs.getInt("stock");
                int nuevoStock = stockActual - cantidadVendida;

                // Actualiza el estock
                String sqlUpdate = "UPDATE productos SET stock = ? WHERE idProducto = ?";
                PreparedStatement pstUpdate = cn.prepareStatement(sqlUpdate);
                pstUpdate.setInt(1, nuevoStock);
                pstUpdate.setInt(2, idProducto);
                pstUpdate.executeUpdate();
            }

            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al restar stock: " + e);
        }
    }

}
